/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Sonde de vie
     * @description Répond dès que le processus est en état de servir.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health/deep": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Sonde de dépendances
     * @description Teste chaque dépendance séparément.
     *
     *     Chacune est signalée individuellement : un état global masquerait
     *     laquelle est tombée, ce qui est précisément l'information utile.
     */
    get: operations["health_deep_health_deep_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/internal/orthanc/authorize": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Autoriser une requête DICOMweb
     * @description Statue sur une requête DICOMweb pour le compte d'Orthanc.
     *
     *     Args:
     *         request: Corps posté par le plugin, validé par Pydantic.
     *         settings: Configuration injectée.
     *
     *     Returns:
     *         Un objet ``{"granted": bool, "validity": int}`` — seul format que
     *         le plugin sait interpréter. ``validity`` n'est jamais nul sur un
     *         refus : côté Orthanc, zéro signifie « cacher pour toujours ».
     */
    post: operations["authorize_internal_orthanc_authorize_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/internal/webhooks/study-stable": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Ingérer une étude complète
     * @description Crée ou actualise l'étude côté métier.
     *
     *     Args:
     *         event: Événement émis par le script Lua d'Orthanc.
     *         settings: Configuration injectée.
     *         x_webhook_secret: Secret partagé, comparé en temps constant.
     *
     *     Returns:
     *         Le résultat de l'ingestion.
     *
     *     Raises:
     *         Unauthorized: Secret absent ou incorrect.
     *         Unprocessable: Clinique émettrice introuvable.
     */
    post: operations["study_stable_internal_webhooks_study_stable_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Profil et organisations de l'utilisateur
     * @description Renvoie l'état de la session courante.
     *
     *     Args:
     *         principal: Appelant authentifié.
     *
     *     Returns:
     *         Le profil, l'organisation active et la liste des appartenances.
     */
    get: operations["read_session_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/active-organization": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Changer d'organisation active
     * @description Bascule l'utilisateur vers une autre de ses organisations.
     *
     *     Le client **doit** enchaîner avec ``supabase.auth.refreshSession()``.
     *     Sans ce second appel, le jeton conserve les anciens claims et rien ne
     *     change côté RLS — c'est un bug silencieux et déroutant.
     *
     *     Args:
     *         body: Organisation cible.
     *         principal: Appelant authentifié.
     *
     *     Returns:
     *         Un accusé assorti du rappel de l'étape suivante.
     *
     *     Raises:
     *         Forbidden: L'appelant n'est pas membre de l'organisation visée.
     */
    post: operations["switch_organization_me_active_organization_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/logout": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Déconnexion
     * @description Révoque les jetons de visualisation encore vivants.
     *
     *     Sans cela, un onglet OHIF resté ouvert continuerait de recevoir des
     *     images jusqu'à quinze minutes après la déconnexion : le jeton de
     *     visualisation a une durée de vie propre, indépendante de la session.
     *
     *     Args:
     *         principal: Appelant authentifié.
     *
     *     Returns:
     *         Le nombre de jetons révoqués.
     */
    post: operations["logout_me_logout_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/me/organization": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Organisation active
     * @description Renvoie l'organisation sous laquelle l'utilisateur agit.
     *
     *     Args:
     *         principal: Appelant disposant d'une organisation active.
     *
     *     Returns:
     *         L'appartenance active.
     */
    get: operations["read_active_organization_me_organization_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reports/{report_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Enregistrer un brouillon
     * @description Fusionne les sections reçues dans le brouillon.
     *
     *     Appelé toutes les cinq secondes pendant la dictée, et à chaque perte
     *     de focus. Le client conserve en parallèle une copie en
     *     ``localStorage`` : le serveur protège de la panne de poste, le
     *     ``localStorage`` de la coupure réseau. À Lomé, il faut les deux.
     *
     *     Args:
     *         report_id: Compte-rendu à mettre à jour.
     *         body: Sections modifiées.
     *         principal: Radiologue authentifié.
     *
     *     Returns:
     *         Le compte-rendu après fusion.
     *
     *     Raises:
     *         Conflict: Compte-rendu absent, appartenant à un autre auteur, ou
     *             déjà signé — donc verrouillé par le trigger.
     */
    patch: operations["autosave_reports__report_id__patch"];
    trace?: never;
  };
  "/reports/{report_id}/pdf": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Télécharger le PDF signé
     * @description Renvoie une URL pré-signée vers le PDF d'un compte-rendu signé.
     *
     *     Le droit d'accès est vérifié par RLS : si la ligne ne remonte pas,
     *     l'appelant n'y a pas droit.
     *
     *     Args:
     *         report_id: Compte-rendu concerné.
     *         principal: Appelant disposant d'une organisation active.
     *
     *     Returns:
     *         L'URL temporaire et sa durée de validité.
     *
     *     Raises:
     *         NotFound: Compte-rendu inaccessible, non signé, ou sans PDF.
     */
    get: operations["download_pdf_reports__report_id__pdf_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reports/{report_id}/sign": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Valider et signer
     * @description Verrouille le compte-rendu, produit le PDF et le dépose sur R2.
     *
     *     **L'ordre des opérations n'est pas arbitraire.** Le PDF est produit et
     *     déposé *avant* que la base ne bascule en ``signed``. Si le dépôt
     *     échoue, il ne reste qu'un objet R2 orphelin, écrasé au prochain essai
     *     puisque la clé dérive de l'identifiant du compte-rendu. L'ordre
     *     inverse laisserait un compte-rendu signé — donc définitivement
     *     verrouillé par le trigger — sans PDF associé.
     *
     *     La bascule finale passe par le rôle de service : elle doit couvrir
     *     dans une seule transaction le compte-rendu, le statut de l'examen et
     *     l'entrée d'audit.
     *
     *     Args:
     *         report_id: Compte-rendu à signer.
     *         principal: Radiologue authentifié.
     *
     *     Returns:
     *         Le compte-rendu signé.
     *
     *     Raises:
     *         NotFound: Compte-rendu inaccessible.
     *         Conflict: Déjà signé, ou signé entre-temps par une autre requête.
     *         Forbidden: L'appelant n'est pas l'auteur du brouillon.
     *         Unprocessable: Une section obligatoire est vide.
     */
    post: operations["sign_reports__report_id__sign_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/studies": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Studies
     * @description Liste les examens visibles par l'appelant.
     *
     *     Le périmètre est décidé par RLS, pas par ce code : une clinique voit
     *     ses propres examens, un radiologue voit le pool des cliniques sous
     *     contrat avec son groupe. Les urgences remontent en tête.
     *
     *     Args:
     *         principal: Appelant disposant d'une organisation active.
     *         status_filter: Restreint à un statut donné.
     *         q: Filtre sur le nom du patient.
     *         limit: Nombre maximal d'examens renvoyés.
     *         offset: Décalage, pour la pagination.
     *
     *     Returns:
     *         Un objet ``{"items": [...], "total": n}``.
     */
    get: operations["list_studies_studies_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/studies/{study_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Study
     * @description Renvoie le détail d'un examen.
     *
     *     Args:
     *         study_id: Examen demandé.
     *         principal: Appelant disposant d'une organisation active.
     *
     *     Returns:
     *         L'examen.
     *
     *     Raises:
     *         NotFound: Examen inexistant ou hors du périmètre de l'appelant.
     *             Les deux cas sont confondus volontairement : les distinguer
     *             révélerait l'existence d'examens d'une clinique concurrente.
     */
    get: operations["get_study_studies__study_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Study
     * @description La clinique complète le renseignement clinique ou signale une urgence.
     */
    patch: operations["update_study_studies__study_id__patch"];
    trace?: never;
  };
  "/studies/{study_id}/claim": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Claim
     * @description Pool commun : le premier radiologue qui ouvre l'examen se l'attribue.
     */
    post: operations["claim_studies__study_id__claim_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/studies/{study_id}/release": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Release
     * @description Rend au pool un examen pris par erreur.
     *
     *     Args:
     *         study_id: Examen à libérer.
     *         principal: Radiologue authentifié.
     *
     *     Returns:
     *         L'examen, redevenu disponible.
     *
     *     Raises:
     *         Forbidden: L'examen n'est pas attribué à l'appelant, ou il est
     *             déjà rendu.
     */
    post: operations["release_studies__study_id__release_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/studies/{study_id}/report": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ouvrir le compte-rendu d'un examen
     * @description Renvoie le compte-rendu d'un examen, en créant le brouillon au besoin.
     *
     *     Un radiologue qui ouvre un examen pour la première fois obtient un
     *     brouillon vide. Une clinique, elle, ne voit rien tant que le document
     *     n'est pas signé — c'est RLS qui l'applique, pas ce code.
     *
     *     Args:
     *         study_id: Examen concerné.
     *         principal: Appelant disposant d'une organisation active.
     *
     *     Returns:
     *         Le compte-rendu, brouillon ou signé.
     *
     *     Raises:
     *         NotFound: Aucun compte-rendu visible, et l'appelant n'est pas
     *             radiologue donc ne peut pas en créer.
     */
    get: operations["get_or_create_draft_studies__study_id__report_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/studies/{study_id}/viewer-token": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Viewer Token
     * @description Émet un jeton opaque limité à cette étude et à quinze minutes.
     *
     *     Le JWT Supabase n'est jamais transmis à Orthanc (AD-4) : s'il fuitait par
     *     un log ou un Referer, il donnerait accès à tout le compte.
     */
    post: operations["viewer_token_studies__study_id__viewer_token_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/templates": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Lister les modèles disponibles
     * @description Renvoie les modèles utilisables par l'appelant.
     *
     *     Les modèles globaux sont listés en dernier : ceux de l'organisation
     *     priment dans l'interface.
     *
     *     Args:
     *         principal: Appelant disposant d'une organisation active.
     *         modality: Restreint aux modèles d'une modalité donnée.
     *         body_part: Restreint aux modèles d'une région donnée.
     *
     *     Returns:
     *         Les modèles visibles, triés organisation d'abord puis par nom.
     */
    get: operations["list_templates_templates_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/verify/{verify_token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Vérifier l'authenticité d'un compte-rendu
     * @description Authentifie un compte-rendu à partir du jeton porté par son QR code.
     *
     *     Le jeton est public mais non devinable. La requête passe par le rôle
     *     de service : l'appelant n'est pas authentifié, il n'y a donc aucun
     *     claim sur lequel RLS pourrait s'appuyer.
     *
     *     Args:
     *         verify_token: Jeton aléatoire encodé dans le QR code du document.
     *
     *     Returns:
     *         Les éléments d'authentification du document.
     *
     *     Raises:
     *         NotFound: Aucun compte-rendu signé ne porte ce jeton.
     */
    get: operations["verify_report_verify__verify_token__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AuthorizationRequest
     * @description Corps posté par le plugin Authorization d'Orthanc.
     *
     *     Les alias reproduisent les noms de champs du plugin, qui utilisent des
     *     tirets. Les champs absents valent ``None`` : le plugin n'envoie que ce
     *     qui a du sens pour le niveau concerné.
     *
     *     Attributes:
     *         level: Niveau de la hiérarchie DICOM concerné, ou ``"system"``
     *             pour une route qui ne désigne pas une ressource.
     *         method: Verbe HTTP en minuscules.
     *         uri: Chemin demandé, **sans chaîne de requête**. Renseigné
     *             uniquement au niveau ``system``.
     *         dicom_uid: Identifiant DICOM de la ressource — ``StudyInstanceUID``
     *             au niveau étude, ``PatientID`` au niveau patient, etc.
     *         orthanc_id: Identifiant interne Orthanc de la ressource.
     *         token_key: Nom du header ou de l'argument d'où vient le jeton.
     *         token_value: Valeur du jeton, préfixe ``Bearer `` compris.
     *         server_id: Valeur de ``WebServiceIdentifier``, utile si plusieurs
     *             Orthanc partagent la même API.
     */
    AuthorizationRequest: {
      /** Dicom-Uid */
      "dicom-uid"?: string | null;
      /**
       * Level
       * @default
       */
      level: string;
      /**
       * Method
       * @default
       */
      method: string;
      /** Orthanc-Id */
      "orthanc-id"?: string | null;
      /** Server-Id */
      "server-id"?: string | null;
      /** Token-Key */
      "token-key"?: string | null;
      /** Token-Value */
      "token-value"?: string | null;
      /** Uri */
      uri?: string | null;
    } & {
      [key: string]: unknown;
    };
    /**
     * ClinicalInfo
     * @description Renseignements que la clinique peut compléter après l'envoi.
     *
     *     Attributes:
     *         clinical_info: Contexte clinique de l'examen. Un champ vide laisse
     *             la valeur existante inchangée.
     *         priority: Passage en urgence, ou retour en routine.
     */
    ClinicalInfo: {
      /** Clinical Info */
      clinical_info?: string | null;
      /** Priority */
      priority?: ("routine" | "urgent") | null;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /**
     * LogoutResult
     * @description Résultat d'une déconnexion.
     *
     *     Attributes:
     *         revoked_viewer_tokens: Nombre de jetons de visualisation
     *             invalidés.
     */
    LogoutResult: {
      /** Revoked Viewer Tokens */
      revoked_viewer_tokens: number;
    };
    /**
     * OrganizationMembership
     * @description Appartenance de l'utilisateur à une organisation.
     *
     *     Attributes:
     *         organization_id: Identifiant de l'organisation.
     *         name: Nom affichable.
     *         kind: ``clinic`` ou ``radiology_group``.
     *         role: Rôle tenu dans cette organisation.
     *         is_active: ``True`` pour celle qui alimente actuellement le JWT.
     */
    OrganizationMembership: {
      /** Is Active */
      is_active: boolean;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
      /** Role */
      role: string;
    };
    /**
     * PdfLink
     * @description Lien de téléchargement temporaire d'un compte-rendu signé.
     *
     *     Attributes:
     *         url: URL R2 pré-signée. Le bucket n'est jamais public.
     *         expires_in: Durée de validité du lien, en secondes.
     */
    PdfLink: {
      /** Expires In */
      expires_in: number;
      /** Url */
      url: string;
    };
    /**
     * Profile
     * @description Fiche de l'utilisateur connecté.
     *
     *     Attributes:
     *         id: Identifiant du profil.
     *         full_name: Nom complet.
     *         title: Titre — « Dr », spécialité.
     *         license_number: Numéro d'ordre, imprimé sur les comptes-rendus.
     *         locale: Langue préférée.
     */
    Profile: {
      /** Full Name */
      full_name: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** License Number */
      license_number?: string | null;
      /**
       * Locale
       * @default fr
       */
      locale: string;
      /** Title */
      title?: string | null;
    };
    /**
     * ReportTemplate
     * @description Modèle de compte-rendu.
     *
     *     Attributes:
     *         id: Identifiant du modèle.
     *         organization_id: Organisation propriétaire, ``None`` si global.
     *         name: Intitulé affiché dans l'éditeur.
     *         modality: Modalité visée — ``CT``, ``MR``, ``CR``…
     *         body_part: Région anatomique visée.
     *         sections: Contenu pré-rempli, une clé par section du
     *             compte-rendu.
     */
    ReportTemplate: {
      /** Body Part */
      body_part: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Modality */
      modality: string | null;
      /** Name */
      name: string;
      /** Organization Id */
      organization_id: string | null;
      /** Sections */
      sections: {
        [key: string]: string;
      };
    };
    /**
     * SectionsPatch
     * @description Fragment de compte-rendu envoyé par l'auto-save.
     *
     *     Attributes:
     *         sections: Sections modifiées, fusionnées avec les existantes.
     *             L'envoi est partiel : l'éditeur ne transmet que ce qui a
     *             changé.
     */
    SectionsPatch: {
      /** Sections */
      sections?: {
        [key: string]: string;
      };
    };
    /**
     * SessionInfo
     * @description État complet de la session, tel que le frontend en a besoin.
     *
     *     Attributes:
     *         profile: Fiche de l'utilisateur, ``None`` si le profil n'existe
     *             pas encore côté métier.
     *         active_organization_id: Organisation active, issue du JWT.
     *         role: Rôle dans cette organisation. Détermine le portail affiché.
     *         organizations: Toutes les appartenances, pour le sélecteur.
     */
    SessionInfo: {
      /** Active Organization Id */
      active_organization_id: string | null;
      /** Organizations */
      organizations: components["schemas"]["OrganizationMembership"][];
      profile: components["schemas"]["Profile"] | null;
      /** Role */
      role: string | null;
    };
    /**
     * StudyStableEvent
     * @description Événement émis quand Orthanc considère une étude complète.
     *
     *     Le déclencheur est ``OnStableStudy``, jamais ``OnStoredInstance`` :
     *     sur un scanner de 2 000 coupes, ce dernier produirait 2 000 appels
     *     pour un seul examen.
     *
     *     Attributes:
     *         orthanc_study_id: Identifiant interne Orthanc de l'étude.
     *         study_instance_uid: ``StudyInstanceUID``, tag (0020,000D).
     *         calling_aet: AE Title de l'émetteur. **Rattachement de
     *             référence** : le nom d'établissement présent dans les tags
     *             DICOM est saisi à la main sur les consoles et n'est pas
     *             fiable.
     *         organization_slug: Rattachement de secours, par identifiant
     *             lisible.
     *         organization_id: Rattachement explicite. Utilisé par les tests et
     *             les reprises manuelles.
     *         patient_name: Nom au format DICOM (``NOM^Prénom``).
     *         patient_id_local: Identifiant patient propre à la clinique.
     *         patient_birthdate: Date de naissance, format DICOM ``AAAAMMJJ``.
     *         patient_sex: ``M``, ``F`` ou ``O``.
     *         modality: Modalité principale — ``CT``, ``MR``, ``CR``, ``US``…
     *         body_part: Région anatomique explorée.
     *         study_date: Date de réalisation de l'examen.
     *         instance_count: Nombre d'instances reçues.
     *         series_count: Nombre de séries reçues.
     */
    StudyStableEvent: {
      /** Body Part */
      body_part?: string | null;
      /** Calling Aet */
      calling_aet?: string | null;
      /**
       * Instance Count
       * @default 0
       */
      instance_count: number;
      /** Modality */
      modality?: string | null;
      /** Organization Id */
      organization_id?: string | null;
      /** Organization Slug */
      organization_slug?: string | null;
      /** Orthanc Study Id */
      orthanc_study_id: string;
      /** Patient Birthdate */
      patient_birthdate?: string | null;
      /** Patient Id Local */
      patient_id_local?: string | null;
      /** Patient Name */
      patient_name?: string | null;
      /** Patient Sex */
      patient_sex?: string | null;
      /**
       * Series Count
       * @default 0
       */
      series_count: number;
      /** Study Date */
      study_date?: string | null;
      /** Study Instance Uid */
      study_instance_uid: string;
    };
    /**
     * StudyStableResult
     * @description Résultat de l'ingestion.
     *
     *     Attributes:
     *         study_id: Identifiant métier de l'étude, côté Supabase.
     *         created: ``True`` si l'étude vient d'être créée ; ``False`` si
     *             l'événement n'a fait qu'actualiser les compteurs.
     *         within_quota: ``False`` si la clinique dépasse son quota mensuel.
     *             L'examen est accepté malgré tout : il est déjà dans le PACS,
     *             et un patient n'a pas à pâtir d'un litige commercial.
     */
    StudyStableResult: {
      /** Created */
      created: boolean;
      /**
       * Study Id
       * Format: uuid
       */
      study_id: string;
      /** Within Quota */
      within_quota: boolean;
    };
    /**
     * SwitchOrganizationRequest
     * @description Demande de bascule vers une autre organisation.
     *
     *     Attributes:
     *         organization_id: Organisation cible. L'appelant doit en être
     *             membre, ce que la base vérifie.
     */
    SwitchOrganizationRequest: {
      /**
       * Organization Id
       * Format: uuid
       */
      organization_id: string;
    };
    /**
     * SwitchOrganizationResult
     * @description Résultat d'une bascule d'organisation.
     *
     *     Attributes:
     *         status: Toujours ``"ok"`` en cas de succès.
     *         next_step: Rappel de l'action que le client **doit** enchaîner.
     */
    SwitchOrganizationResult: {
      /**
       * Next Step
       * @default refreshSession
       */
      next_step: string;
      /**
       * Status
       * @default ok
       */
      status: string;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VerificationResult
     * @description Éléments permettant d'authentifier un compte-rendu imprimé.
     *
     *     Attributes:
     *         valid: Toujours ``True`` — une vérification négative renvoie 404.
     *         patient_initial: Première lettre du nom, suivie d'un point.
     *             Suffit à recouper avec le document en main, sans divulguer
     *             l'identité.
     *         clinic: Clinique émettrice.
     *         modality: Modalité de l'examen.
     *         study_date: Date de l'examen, au format ISO.
     *         signed_at: Horodatage de la signature, au format ISO.
     *         radiologist: Titre et nom du signataire.
     *         license_number: Numéro d'ordre du signataire.
     *         sha256: Empreinte du PDF. Le porteur du document recalcule
     *             l'empreinte de son exemplaire et la compare — c'est ici
     *             qu'elle figure, et non dans le PDF, car l'empreinte d'un
     *             fichier ne peut pas être écrite à l'intérieur de ce fichier.
     */
    VerificationResult: {
      /** Clinic */
      clinic: string;
      /** License Number */
      license_number: string | null;
      /** Modality */
      modality: string | null;
      /** Patient Initial */
      patient_initial: string | null;
      /** Radiologist */
      radiologist: string;
      /** Sha256 */
      sha256: string | null;
      /** Signed At */
      signed_at: string;
      /** Study Date */
      study_date: string | null;
      /**
       * Valid
       * @default true
       */
      valid: boolean;
    };
    /**
     * ViewerToken
     * @description Jeton d'ouverture d'une étude dans le viewer.
     *
     *     Attributes:
     *         token: Jeton opaque, valable pour cette étude uniquement.
     *         expires_in: Durée de vie restante, en secondes.
     *         viewer_url: URL complète à ouvrir. OHIF y lit ``?token=``,
     *             l'injecte en en-tête ``Authorization`` puis le retire de
     *             l'URL.
     */
    ViewerToken: {
      /** Expires In */
      expires_in: number;
      /** Token */
      token: string;
      /** Viewer Url */
      viewer_url: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  health_deep_health_deep_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: string;
          };
        };
      };
    };
  };
  authorize_internal_orthanc_authorize_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthorizationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  study_stable_internal_webhooks_study_stable_post: {
    parameters: {
      query?: never;
      header?: {
        "x-webhook-secret"?: string;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StudyStableEvent"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StudyStableResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_session_me_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionInfo"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  switch_organization_me_active_organization_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwitchOrganizationRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SwitchOrganizationResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  logout_me_logout_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LogoutResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_active_organization_me_organization_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrganizationMembership"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  autosave_reports__report_id__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SectionsPatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  download_pdf_reports__report_id__pdf_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PdfLink"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  sign_reports__report_id__sign_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        report_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_studies_studies_get: {
    parameters: {
      query?: {
        status?: string | null;
        /** @description Recherche sur le nom du patient */
        q?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_study_studies__study_id__get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_study_studies__study_id__patch: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ClinicalInfo"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  claim_studies__study_id__claim_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  release_studies__study_id__release_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_or_create_draft_studies__study_id__report_get: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  viewer_token_studies__study_id__viewer_token_post: {
    parameters: {
      query?: never;
      header?: {
        authorization?: string | null;
      };
      path: {
        study_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ViewerToken"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_templates_templates_get: {
    parameters: {
      query?: {
        /** @description Filtre par modalité */
        modality?: string | null;
        /** @description Filtre par région */
        body_part?: string | null;
      };
      header?: {
        authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReportTemplate"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_report_verify__verify_token__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        verify_token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["VerificationResult"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
